# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QTableWidgetItem
from PyQt5 import QtCore, QtGui, QtWidgets
from Tools.DatabaseOperation import SQL
from threading import Thread
class Ui_Form(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1198, 739)
        self.frame_Control = QtWidgets.QFrame(Form)
        self.frame_Control.setGeometry(QtCore.QRect(0, 0, 1198, 740))
        self.frame_Control.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#fafbfd;\n"
"   border:0px;\n"
"}")
        self.frame_Control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Control.setObjectName("frame_Control")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_Control)
        self.verticalLayout_23.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_TopBar_2 = QtWidgets.QFrame(self.frame_Control)
        self.frame_TopBar_2.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_TopBar_2.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_TopBar_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_TopBar_2.setStyleSheet("QFrame{\n"
"background-color: #ffffff;\n"
"border:1px solid #edf2fa;\n"
"}")
        self.frame_TopBar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopBar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopBar_2.setObjectName("frame_TopBar_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_TopBar_2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_PerfilName_2 = QtWidgets.QLabel(self.frame_TopBar_2)
        self.label_PerfilName_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_PerfilName_2.setStyleSheet("QLabel{\n"
"color:rgb(204, 207, 211);\n"
"    font-size:15px;\n"
"    border:0px;\n"
"\n"
"}\n"
"\n"
"")
        self.label_PerfilName_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PerfilName_2.setObjectName("label_PerfilName_2")
        self.horizontalLayout_20.addWidget(self.label_PerfilName_2)
        self.pushButton_Perfil_2 = QtWidgets.QPushButton(self.frame_TopBar_2)
        self.pushButton_Perfil_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_Perfil_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_Perfil_2.setStyleSheet("QPushButton{\n"
"background-color:#e5faf8;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_Perfil_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/user-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Perfil_2.setIcon(icon)
        self.pushButton_Perfil_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Perfil_2.setObjectName("pushButton_Perfil_2")
        self.horizontalLayout_20.addWidget(self.pushButton_Perfil_2)
        self.pushButton_Notifications_2 = QtWidgets.QPushButton(self.frame_TopBar_2)
        self.pushButton_Notifications_2.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_Notifications_2.setMaximumSize(QtCore.QSize(50, 30))
        self.pushButton_Notifications_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Notifications_2.setStyleSheet("QPushButton{\n"
"background-color:#e5faf8;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Notifications_2.setIcon(icon1)
        self.pushButton_Notifications_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Notifications_2.setObjectName("pushButton_Notifications_2")
        self.horizontalLayout_20.addWidget(self.pushButton_Notifications_2)
        self.frame_TopBarSpace_2 = QtWidgets.QFrame(self.frame_TopBar_2)
        self.frame_TopBarSpace_2.setStyleSheet("QFrame{border:0px;}")
        self.frame_TopBarSpace_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopBarSpace_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopBarSpace_2.setObjectName("frame_TopBarSpace_2")
        self.horizontalLayout_20.addWidget(self.frame_TopBarSpace_2)
        self.label_LastAccess_2 = QtWidgets.QLabel(self.frame_TopBar_2)
        self.label_LastAccess_2.setMinimumSize(QtCore.QSize(160, 0))
        self.label_LastAccess_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_LastAccess_2.setStyleSheet("QLabel{\n"
"color:rgb(204, 207, 211);\n"
"    font-size:15px;\n"
"    border:0px;\n"
"\n"
"}\n"
"\n"
"")
        self.label_LastAccess_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_LastAccess_2.setObjectName("label_LastAccess_2")
        self.horizontalLayout_20.addWidget(self.label_LastAccess_2)
        self.pushButton_LastAccess_2 = QtWidgets.QPushButton(self.frame_TopBar_2)
        self.pushButton_LastAccess_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_LastAccess_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_LastAccess_2.setStyleSheet("QPushButton{\n"
"background-color:#e5faf8;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_LastAccess_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/clock-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LastAccess_2.setIcon(icon2)
        self.pushButton_LastAccess_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_LastAccess_2.setObjectName("pushButton_LastAccess_2")
        self.horizontalLayout_20.addWidget(self.pushButton_LastAccess_2)
        self.frame_LeftControlBar = QtWidgets.QFrame(self.frame_TopBar_2)
        self.frame_LeftControlBar.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_LeftControlBar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_LeftControlBar.setStyleSheet("QFrame{\n"
"background-color: #ffffff;\n"
"border:1px solid #edf2fa;\n"
"}")
        self.frame_LeftControlBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LeftControlBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LeftControlBar.setObjectName("frame_LeftControlBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_LeftControlBar)
        self.verticalLayout.setContentsMargins(0, 9, 0, -1)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_Logo = QtWidgets.QFrame(self.frame_LeftControlBar)
        self.frame_Logo.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_Logo.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_Logo.setStyleSheet("QFrame{\n"
"    background-color:#fff;\n"
"    border:0px;\n"
"    color:#070000;\n"
"}\n"
"")
        self.frame_Logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Logo.setObjectName("frame_Logo")
        self.label_LogoNameDesc = QtWidgets.QLabel(self.frame_Logo)
        self.label_LogoNameDesc.setGeometry(QtCore.QRect(0, 60, 191, 15))
        self.label_LogoNameDesc.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_LogoNameDesc.setStyleSheet("QLabel{\n"
"\n"
"    font-size:16px;\n"
"    border:0px;\n"
"color:rgb(204, 207, 211);\n"
"\n"
"}")
        self.label_LogoNameDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LogoNameDesc.setObjectName("label_LogoNameDesc")
        self.label_LogoName = QtWidgets.QLabel(self.frame_Logo)
        self.label_LogoName.setGeometry(QtCore.QRect(0, 20, 191, 42))
        self.label_LogoName.setStyleSheet("QLabel{\n"
"color:#04c9b7;\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"  text-align:center;\n"
"\n"
"}")
        self.label_LogoName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LogoName.setObjectName("label_LogoName")
        self.verticalLayout.addWidget(self.frame_Logo)
        self.pushButton_DashBoard = QtWidgets.QPushButton(self.frame_LeftControlBar)
        self.pushButton_DashBoard.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_DashBoard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_DashBoard.setStyleSheet("QPushButton{\n"
"    background-color:#e5faf8;\n"
"    border:0px;\n"
"    color:#0bc9b7;\n"
"    font-weight: bold;\n"
"font-size:15px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/stopwatch-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashBoard.setIcon(icon3)
        self.pushButton_DashBoard.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_DashBoard.setObjectName("pushButton_DashBoard")
        self.verticalLayout.addWidget(self.pushButton_DashBoard)
        self.pushButton_QuickStart = QtWidgets.QPushButton(self.frame_LeftControlBar)
        self.pushButton_QuickStart.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_QuickStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QuickStart.setStyleSheet("QPushButton{\n"
"    background-color:#fff;\n"
"    border:0px;\n"
"    color:#070000;\n"
"font-size:15px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#e5faf8;\n"
"    border:0px;\n"
"    color:#070000;\n"
"    font-weight: bold;\n"
"font-size:15px;\n"
"text-align:left;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/target.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_QuickStart.setIcon(icon4)
        self.pushButton_QuickStart.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_QuickStart.setObjectName("pushButton_QuickStart")
        self.verticalLayout.addWidget(self.pushButton_QuickStart)
        self.pushButton_Assets = QtWidgets.QPushButton(self.frame_LeftControlBar)
        self.pushButton_Assets.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_Assets.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Assets.setStyleSheet("QPushButton{\n"
"    background-color:#fff;\n"
"    border:0px;\n"
"    color:#070000;\n"
"font-size:15px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#e5faf8;\n"
"    border:0px;\n"
"    color:#070000;\n"
"    font-weight: bold;\n"
"font-size:15px;\n"
"text-align:left;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/windows-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Assets.setIcon(icon5)
        self.pushButton_Assets.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Assets.setObjectName("pushButton_Assets")
        self.verticalLayout.addWidget(self.pushButton_Assets)
        self.pushButton_Report = QtWidgets.QPushButton(self.frame_LeftControlBar)
        self.pushButton_Report.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_Report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Report.setStyleSheet("QPushButton{\n"
"    background-color:#fff;\n"
"    border:0px;\n"
"    color:#070000;\n"
"font-size:15px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#e5faf8;\n"
"    border:0px;\n"
"    color:#070000;\n"
"    font-weight: bold;\n"
"font-size:15px;\n"
"text-align:left;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Report.setIcon(icon6)
        self.pushButton_Report.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Report.setObjectName("pushButton_Report")
        self.verticalLayout.addWidget(self.pushButton_Report)
        self.pushButton_Config = QtWidgets.QPushButton(self.frame_LeftControlBar)
        self.pushButton_Config.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_Config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Config.setStyleSheet("QPushButton{\n"
"    background-color:#fff;\n"
"    border:0px;\n"
"    color:#070000;\n"
"font-size:15px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#e5faf8;\n"
"    border:0px;\n"
"    color:#070000;\n"
"    font-weight: bold;\n"
"font-size:15px;\n"
"text-align:left;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/settings-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Config.setIcon(icon7)
        self.pushButton_Config.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Config.setObjectName("pushButton_Config")
        self.verticalLayout.addWidget(self.pushButton_Config)
        self.frame_LeftControlBarSpace = QtWidgets.QFrame(self.frame_LeftControlBar)
        self.frame_LeftControlBarSpace.setStyleSheet("QFrame{\n"
"\n"
"border:0px;\n"
"}")
        self.frame_LeftControlBarSpace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LeftControlBarSpace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LeftControlBarSpace.setObjectName("frame_LeftControlBarSpace")
        self.formLayout = QtWidgets.QFormLayout(self.frame_LeftControlBarSpace)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout.addWidget(self.frame_LeftControlBarSpace)
        self.pushButton_About = QtWidgets.QPushButton(self.frame_LeftControlBar)
        self.pushButton_About.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_About.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_About.setStyleSheet("QPushButton{\n"
"    background-color:#fff;\n"
"    border:0px;\n"
"    color:rgb(186, 189, 182);\n"
"\n"
"font-size:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#e5faf8;\n"
"    border:0px;\n"
"    color:#070000;\n"
"    font-weight: bold;\n"
"font-size:15px;\n"
"}")
        self.pushButton_About.setObjectName("pushButton_About")
        self.verticalLayout.addWidget(self.pushButton_About)
        self.horizontalLayout_20.addWidget(self.frame_LeftControlBar)
        self.label_IpInfo_2 = QtWidgets.QLabel(self.frame_TopBar_2)
        self.label_IpInfo_2.setMinimumSize(QtCore.QSize(160, 0))
        self.label_IpInfo_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_IpInfo_2.setStyleSheet("QLabel{\n"
"color:rgb(204, 207, 211);\n"
"    font-size:15px;\n"
"    border:0px;\n"
"\n"
"}\n"
"\n"
"")
        self.label_IpInfo_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_IpInfo_2.setObjectName("label_IpInfo_2")
        self.horizontalLayout_20.addWidget(self.label_IpInfo_2)
        self.pushButton_InfoIo_2 = QtWidgets.QPushButton(self.frame_TopBar_2)
        self.pushButton_InfoIo_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_InfoIo_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_InfoIo_2.setStyleSheet("QPushButton{\n"
"background-color:#e5faf8;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_InfoIo_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/placeholder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_InfoIo_2.setIcon(icon8)
        self.pushButton_InfoIo_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_InfoIo_2.setObjectName("pushButton_InfoIo_2")
        self.horizontalLayout_20.addWidget(self.pushButton_InfoIo_2)
        self.verticalLayout_23.addWidget(self.frame_TopBar_2)
        self.stackedWidget_Control_2 = QtWidgets.QStackedWidget(self.frame_Control)
        self.stackedWidget_Control_2.setStyleSheet("QLabel{\n"
"\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"\n"
"\n"
"}")
        self.stackedWidget_Control_2.setObjectName("stackedWidget_Control_2")
        self.page_DashBoard_2 = QtWidgets.QWidget()
        self.page_DashBoard_2.setStyleSheet("QWidget{\n"
"    background-color:#fafbfd;\n"
"    border:0px;\n"
"}")
        self.page_DashBoard_2.setObjectName("page_DashBoard_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.page_DashBoard_2)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_CentralControl_7 = QtWidgets.QFrame(self.page_DashBoard_2)
        self.frame_CentralControl_7.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#fafbfd;\n"
"   border:0px;\n"
"}")
        self.frame_CentralControl_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralControl_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralControl_7.setObjectName("frame_CentralControl_7")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_CentralControl_7)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_7 = QtWidgets.QFrame(self.frame_CentralControl_7)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_Hello_2 = QtWidgets.QLabel(self.frame_7)
        self.label_Hello_2.setStyleSheet("QLabel{\n"
"\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"\n"
"\n"
"}")
        self.label_Hello_2.setObjectName("label_Hello_2")
        self.horizontalLayout_21.addWidget(self.label_Hello_2)
        self.verticalLayout_25.addWidget(self.frame_7)
        self.frame_CentralTop_2 = QtWidgets.QFrame(self.frame_CentralControl_7)
        self.frame_CentralTop_2.setMinimumSize(QtCore.QSize(0, 220))
        self.frame_CentralTop_2.setMaximumSize(QtCore.QSize(16777215, 220))
        self.frame_CentralTop_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralTop_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralTop_2.setObjectName("frame_CentralTop_2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_CentralTop_2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_DashHostDiscovered_2 = QtWidgets.QFrame(self.frame_CentralTop_2)
        self.frame_DashHostDiscovered_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_DashHostDiscovered_2.setStyleSheet("QFrame{\n"
"border:1px solid #edf2fa;\n"
"background-color:#fff;\n"
"border-radius:10px;\n"
"text-align:center;\n"
"}")
        self.frame_DashHostDiscovered_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashHostDiscovered_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashHostDiscovered_2.setObjectName("frame_DashHostDiscovered_2")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_DashHostDiscovered_2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_DashHostDiscovered_2 = QtWidgets.QLabel(self.frame_DashHostDiscovered_2)
        self.label_DashHostDiscovered_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:20px;\n"
"    border:0px;\n"
"\n"
"}")
        self.label_DashHostDiscovered_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DashHostDiscovered_2.setObjectName("label_DashHostDiscovered_2")
        self.verticalLayout_26.addWidget(self.label_DashHostDiscovered_2)
        self.frame_12 = QtWidgets.QFrame(self.frame_DashHostDiscovered_2)
        self.frame_12.setStyleSheet("QFrame{border:0px;}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_DashHostDiscovered_2 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_DashHostDiscovered_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_DashHostDiscovered_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_DashHostDiscovered_2.setStyleSheet("QPushButton{\n"
"background-color:#04c9b7;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_DashHostDiscovered_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/star-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashHostDiscovered_2.setIcon(icon9)
        self.pushButton_DashHostDiscovered_2.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_DashHostDiscovered_2.setObjectName("pushButton_DashHostDiscovered_2")
        self.horizontalLayout_23.addWidget(self.pushButton_DashHostDiscovered_2)
        self.label_CountDashHostDiscovered_2 = QtWidgets.QLabel(self.frame_12)
        self.label_CountDashHostDiscovered_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:30px;\n"
"    border:0px;\n"
"    font-weight: bold;\n"
"\n"
"}")
        self.label_CountDashHostDiscovered_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CountDashHostDiscovered_2.setObjectName("label_CountDashHostDiscovered_2")
        self.horizontalLayout_23.addWidget(self.label_CountDashHostDiscovered_2)
        self.verticalLayout_26.addWidget(self.frame_12)
        self.frame_Line_2 = QtWidgets.QFrame(self.frame_DashHostDiscovered_2)
        self.frame_Line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Line_2.setStyleSheet("QFrame{\n"
"border:0px;\n"
"background-color:#edf2fa;\n"
"border-radius:0px;\n"
"}")
        self.frame_Line_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Line_2.setObjectName("frame_Line_2")
        self.verticalLayout_26.addWidget(self.frame_Line_2)
        self.label_DescDashHostDiscovered_2 = QtWidgets.QLabel(self.frame_DashHostDiscovered_2)
        self.label_DescDashHostDiscovered_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:16px;\n"
"    border:0px;\n"
"color:rgb(204, 207, 211);\n"
"\n"
"}")
        self.label_DescDashHostDiscovered_2.setText("")
        self.label_DescDashHostDiscovered_2.setObjectName("label_DescDashHostDiscovered_2")
        self.verticalLayout_26.addWidget(self.label_DescDashHostDiscovered_2)
        self.horizontalLayout_22.addWidget(self.frame_DashHostDiscovered_2)
        self.frame_CentralSpace1_2 = QtWidgets.QFrame(self.frame_CentralTop_2)
        self.frame_CentralSpace1_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_CentralSpace1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralSpace1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralSpace1_2.setObjectName("frame_CentralSpace1_2")
        self.horizontalLayout_22.addWidget(self.frame_CentralSpace1_2)
        self.frame_DashScanExecuted_2 = QtWidgets.QFrame(self.frame_CentralTop_2)
        self.frame_DashScanExecuted_2.setStyleSheet("QFrame{\n"
"border:1px solid #edf2fa;\n"
"background-color:#fff;\n"
"border-radius:10px;\n"
"}")
        self.frame_DashScanExecuted_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashScanExecuted_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashScanExecuted_2.setObjectName("frame_DashScanExecuted_2")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_DashScanExecuted_2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_DashScanExecuted_2 = QtWidgets.QLabel(self.frame_DashScanExecuted_2)
        self.label_DashScanExecuted_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:20px;\n"
"    border:0px;\n"
"\n"
"}")
        self.label_DashScanExecuted_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DashScanExecuted_2.setObjectName("label_DashScanExecuted_2")
        self.verticalLayout_27.addWidget(self.label_DashScanExecuted_2)
        self.frame_13 = QtWidgets.QFrame(self.frame_DashScanExecuted_2)
        self.frame_13.setStyleSheet("QFrame{border:0px;}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_DashScanExecuted_2 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_DashScanExecuted_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_DashScanExecuted_2.setStyleSheet("QPushButton{\n"
"background-color:#04c9b7;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_DashScanExecuted_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/search-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashScanExecuted_2.setIcon(icon10)
        self.pushButton_DashScanExecuted_2.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_DashScanExecuted_2.setObjectName("pushButton_DashScanExecuted_2")
        self.horizontalLayout_24.addWidget(self.pushButton_DashScanExecuted_2)
        self.label_CountDashScanExecuted_2 = QtWidgets.QLabel(self.frame_13)
        self.label_CountDashScanExecuted_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:30px;\n"
"    border:0px;\n"
"    font-weight: bold;\n"
"\n"
"}")
        self.label_CountDashScanExecuted_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CountDashScanExecuted_2.setObjectName("label_CountDashScanExecuted_2")
        self.horizontalLayout_24.addWidget(self.label_CountDashScanExecuted_2)
        self.verticalLayout_27.addWidget(self.frame_13)
        self.frame_Line_4 = QtWidgets.QFrame(self.frame_DashScanExecuted_2)
        self.frame_Line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Line_4.setStyleSheet("QFrame{\n"
"border:0px;\n"
"background-color:#edf2fa;\n"
"border-radius:0px;\n"
"}")
        self.frame_Line_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Line_4.setObjectName("frame_Line_4")
        self.verticalLayout_27.addWidget(self.frame_Line_4)
        self.label_DescDashScanExecuted_2 = QtWidgets.QLabel(self.frame_DashScanExecuted_2)
        self.label_DescDashScanExecuted_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:16px;\n"
"    border:0px;\n"
"color:rgb(204, 207, 211);\n"
"\n"
"}")
        self.label_DescDashScanExecuted_2.setText("")
        self.label_DescDashScanExecuted_2.setObjectName("label_DescDashScanExecuted_2")
        self.verticalLayout_27.addWidget(self.label_DescDashScanExecuted_2)
        self.horizontalLayout_22.addWidget(self.frame_DashScanExecuted_2)
        self.frame_CentralSpace2_2 = QtWidgets.QFrame(self.frame_CentralTop_2)
        self.frame_CentralSpace2_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_CentralSpace2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralSpace2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralSpace2_2.setObjectName("frame_CentralSpace2_2")
        self.horizontalLayout_22.addWidget(self.frame_CentralSpace2_2)
        self.frame_DashDomains_2 = QtWidgets.QFrame(self.frame_CentralTop_2)
        self.frame_DashDomains_2.setStyleSheet("QFrame{\n"
"border:1px solid #edf2fa;\n"
"background-color:#fff;\n"
"border-radius:10px;\n"
"}")
        self.frame_DashDomains_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashDomains_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashDomains_2.setObjectName("frame_DashDomains_2")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_DashDomains_2)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_DashDomains_2 = QtWidgets.QLabel(self.frame_DashDomains_2)
        self.label_DashDomains_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:20px;\n"
"    border:0px;\n"
"\n"
"}")
        self.label_DashDomains_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DashDomains_2.setObjectName("label_DashDomains_2")
        self.verticalLayout_28.addWidget(self.label_DashDomains_2)
        self.frame_14 = QtWidgets.QFrame(self.frame_DashDomains_2)
        self.frame_14.setStyleSheet("QFrame{border:0px;}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_DashDomains_2 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_DashDomains_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_DashDomains_2.setStyleSheet("QPushButton{\n"
"background-color:#04c9b7;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_DashDomains_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/cloud-computing-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashDomains_2.setIcon(icon11)
        self.pushButton_DashDomains_2.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_DashDomains_2.setObjectName("pushButton_DashDomains_2")
        self.horizontalLayout_25.addWidget(self.pushButton_DashDomains_2)
        self.label_CountDashDomains_2 = QtWidgets.QLabel(self.frame_14)
        self.label_CountDashDomains_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:30px;\n"
"    border:0px;\n"
"    font-weight: bold;\n"
"\n"
"}")
        self.label_CountDashDomains_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CountDashDomains_2.setObjectName("label_CountDashDomains_2")
        self.horizontalLayout_25.addWidget(self.label_CountDashDomains_2)
        self.verticalLayout_28.addWidget(self.frame_14)
        self.frame_Line_8 = QtWidgets.QFrame(self.frame_DashDomains_2)
        self.frame_Line_8.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Line_8.setStyleSheet("QFrame{\n"
"border:0px;\n"
"background-color:#edf2fa;\n"
"border-radius:0px;\n"
"}")
        self.frame_Line_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Line_8.setObjectName("frame_Line_8")
        self.verticalLayout_28.addWidget(self.frame_Line_8)
        self.label_DescDashDomains_2 = QtWidgets.QLabel(self.frame_DashDomains_2)
        self.label_DescDashDomains_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:16px;\n"
"    border:0px;\n"
"color:rgb(204, 207, 211);\n"
"\n"
"}")
        self.label_DescDashDomains_2.setText("")
        self.label_DescDashDomains_2.setObjectName("label_DescDashDomains_2")
        self.verticalLayout_28.addWidget(self.label_DescDashDomains_2)
        self.horizontalLayout_22.addWidget(self.frame_DashDomains_2)
        self.frame_CentralSpace3_2 = QtWidgets.QFrame(self.frame_CentralTop_2)
        self.frame_CentralSpace3_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_CentralSpace3_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralSpace3_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralSpace3_2.setObjectName("frame_CentralSpace3_2")
        self.horizontalLayout_22.addWidget(self.frame_CentralSpace3_2)
        self.frame_DashTotalVuln_2 = QtWidgets.QFrame(self.frame_CentralTop_2)
        self.frame_DashTotalVuln_2.setStyleSheet("QFrame{\n"
"border:1px solid #edf2fa;\n"
"background-color:#fff;\n"
"border-radius:10px;\n"
"}")
        self.frame_DashTotalVuln_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashTotalVuln_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashTotalVuln_2.setObjectName("frame_DashTotalVuln_2")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_DashTotalVuln_2)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_DashHostDiscovered_9 = QtWidgets.QLabel(self.frame_DashTotalVuln_2)
        self.label_DashHostDiscovered_9.setStyleSheet("QLabel{\n"
"\n"
"    font-size:20px;\n"
"    border:0px;\n"
"\n"
"}")
        self.label_DashHostDiscovered_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DashHostDiscovered_9.setObjectName("label_DashHostDiscovered_9")
        self.verticalLayout_29.addWidget(self.label_DashHostDiscovered_9)
        self.frame_15 = QtWidgets.QFrame(self.frame_DashTotalVuln_2)
        self.frame_15.setStyleSheet("QFrame{border:0px;}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.pushButton_DashTotalVuln_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_DashTotalVuln_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_DashTotalVuln_2.setStyleSheet("QPushButton{\n"
"background-color:#04c9b7;\n"
"border:0px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_DashTotalVuln_2.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashTotalVuln_2.setIcon(icon12)
        self.pushButton_DashTotalVuln_2.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_DashTotalVuln_2.setObjectName("pushButton_DashTotalVuln_2")
        self.horizontalLayout_26.addWidget(self.pushButton_DashTotalVuln_2)
        self.label_CountDashTotalVuln_2 = QtWidgets.QLabel(self.frame_15)
        self.label_CountDashTotalVuln_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:30px;\n"
"    border:0px;\n"
"    font-weight: bold;\n"
"\n"
"}")
        self.label_CountDashTotalVuln_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CountDashTotalVuln_2.setObjectName("label_CountDashTotalVuln_2")
        self.horizontalLayout_26.addWidget(self.label_CountDashTotalVuln_2)
        self.verticalLayout_29.addWidget(self.frame_15)
        self.frame_Line_9 = QtWidgets.QFrame(self.frame_DashTotalVuln_2)
        self.frame_Line_9.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Line_9.setStyleSheet("QFrame{\n"
"border:0px;\n"
"background-color:#edf2fa;\n"
"border-radius:0px;\n"
"}")
        self.frame_Line_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Line_9.setObjectName("frame_Line_9")
        self.verticalLayout_29.addWidget(self.frame_Line_9)
        self.label_DescDashTotalVuln_2 = QtWidgets.QLabel(self.frame_DashTotalVuln_2)
        self.label_DescDashTotalVuln_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:16px;\n"
"    border:0px;\n"
"color:rgb(204, 207, 211);\n"
"\n"
"}")
        self.label_DescDashTotalVuln_2.setText("")
        self.label_DescDashTotalVuln_2.setObjectName("label_DescDashTotalVuln_2")
        self.verticalLayout_29.addWidget(self.label_DescDashTotalVuln_2)
        self.horizontalLayout_22.addWidget(self.frame_DashTotalVuln_2)
        self.verticalLayout_25.addWidget(self.frame_CentralTop_2)
        self.frame_CentralBottom_7 = QtWidgets.QFrame(self.frame_CentralControl_7)
        self.frame_CentralBottom_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralBottom_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralBottom_7.setObjectName("frame_CentralBottom_7")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_CentralBottom_7)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.frame_CentralLeft_2 = QtWidgets.QFrame(self.frame_CentralBottom_7)
        self.frame_CentralLeft_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralLeft_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralLeft_2.setObjectName("frame_CentralLeft_2")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_CentralLeft_2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_Vulnerabilities_2 = QtWidgets.QFrame(self.frame_CentralLeft_2)
        self.frame_Vulnerabilities_2.setStyleSheet("QFrame{\n"
"border:1px solid #edf2fa;\n"
"background-color:#fff;\n"
"border-radius:10px;\n"
"}")
        self.frame_Vulnerabilities_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Vulnerabilities_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Vulnerabilities_2.setObjectName("frame_Vulnerabilities_2")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_Vulnerabilities_2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.lbl_Vulnerabilities_2 = QtWidgets.QLabel(self.frame_Vulnerabilities_2)
        self.lbl_Vulnerabilities_2.setStyleSheet("QLabel{\n"
"\n"
"        font-size:25px;\n"
"    border:0px;\n"
"\n"
"}")
        self.lbl_Vulnerabilities_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Vulnerabilities_2.setObjectName("lbl_Vulnerabilities_2")
        self.verticalLayout_31.addWidget(self.lbl_Vulnerabilities_2)
        self.lbl_VulnerabilitiesDesc_2 = QtWidgets.QLabel(self.frame_Vulnerabilities_2)
        self.lbl_VulnerabilitiesDesc_2.setStyleSheet("QLabel{\n"
"\n"
"    font-size:16px;\n"
"    border:0px;\n"
"color:rgb(204, 207, 211);\n"
"\n"
"}")
        self.lbl_VulnerabilitiesDesc_2.setText("")
        self.lbl_VulnerabilitiesDesc_2.setObjectName("lbl_VulnerabilitiesDesc_2")
        self.verticalLayout_31.addWidget(self.lbl_VulnerabilitiesDesc_2)
        self.tableWidget_Vulnerabilities_2 = QtWidgets.QTableWidget(self.frame_Vulnerabilities_2)
        self.tableWidget_Vulnerabilities_2.setStyleSheet("QTableWidget {    \n"
"    background-color: #fff;\n"
"    padding: 10px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(204, 207, 211);\n"
"    color:#000;\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: #e5faf8;\n"
"    color:#000;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView{\n"
"   background-color:#04c9b7;\n"
"    border: 1px solid rgb(204, 207, 211);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(204, 207, 211);\n"
"    border-right: 1px solid rgb(204, 207, 211);\n"
"    color:#fff;\n"
"    font-size:15px;\n"
"    border-radius: 0px;\n"
"}\n"
"")
        self.tableWidget_Vulnerabilities_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Vulnerabilities_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Vulnerabilities_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_Vulnerabilities_2.setShowGrid(True)
        self.tableWidget_Vulnerabilities_2.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_Vulnerabilities_2.setObjectName("tableWidget_Vulnerabilities_2")
        self.tableWidget_Vulnerabilities_2.setColumnCount(3)
        self.tableWidget_Vulnerabilities_2.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities_2.setItem(22, 2, item)
        self.tableWidget_Vulnerabilities_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Vulnerabilities_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Vulnerabilities_2.verticalHeader().setVisible(False)
        self.tableWidget_Vulnerabilities_2.verticalHeader().setHighlightSections(True)
        self.verticalLayout_31.addWidget(self.tableWidget_Vulnerabilities_2)
        self.verticalLayout_30.addWidget(self.frame_Vulnerabilities_2)
        self.horizontalLayout_27.addWidget(self.frame_CentralLeft_2)
        self.verticalLayout_25.addWidget(self.frame_CentralBottom_7)
        self.verticalLayout_24.addWidget(self.frame_CentralControl_7)
        self.stackedWidget_Control_2.addWidget(self.page_DashBoard_2)
        self.page_QuickStart_2 = QtWidgets.QWidget()
        self.page_QuickStart_2.setStyleSheet("QWidget{\n"
"    background-color:#fafbfd;\n"
"    border:0px;\n"
"}")
        self.page_QuickStart_2.setObjectName("page_QuickStart_2")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.page_QuickStart_2)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.frame_CentralControl_8 = QtWidgets.QFrame(self.page_QuickStart_2)
        self.frame_CentralControl_8.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#fafbfd;\n"
"   border:0px;\n"
"}")
        self.frame_CentralControl_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralControl_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralControl_8.setObjectName("frame_CentralControl_8")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_CentralControl_8)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_16 = QtWidgets.QFrame(self.frame_CentralControl_8)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_8 = QtWidgets.QLabel(self.frame_16)
        self.label_8.setStyleSheet("QLabel{\n"
"\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"\n"
"\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_28.addWidget(self.label_8)
        self.verticalLayout_35.addWidget(self.frame_16)
        self.frame_CentralBottom_8 = QtWidgets.QFrame(self.frame_CentralControl_8)
        self.frame_CentralBottom_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralBottom_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralBottom_8.setObjectName("frame_CentralBottom_8")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_CentralBottom_8)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_35.addWidget(self.frame_CentralBottom_8)
        self.verticalLayout_34.addWidget(self.frame_CentralControl_8)
        self.stackedWidget_Control_2.addWidget(self.page_QuickStart_2)
        self.page_Assets_2 = QtWidgets.QWidget()
        self.page_Assets_2.setStyleSheet("QWidget{\n"
"    background-color:#fafbfd;\n"
"    border:0px;\n"
"}")
        self.page_Assets_2.setObjectName("page_Assets_2")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.page_Assets_2)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.frame_CentralControl_9 = QtWidgets.QFrame(self.page_Assets_2)
        self.frame_CentralControl_9.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#fafbfd;\n"
"   border:0px;\n"
"}")
        self.frame_CentralControl_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralControl_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralControl_9.setObjectName("frame_CentralControl_9")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_CentralControl_9)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.frame_17 = QtWidgets.QFrame(self.frame_CentralControl_9)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_9 = QtWidgets.QLabel(self.frame_17)
        self.label_9.setStyleSheet("QLabel{\n"
"\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"\n"
"\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_30.addWidget(self.label_9)
        self.verticalLayout_37.addWidget(self.frame_17)
        self.frame_CentralBottom_9 = QtWidgets.QFrame(self.frame_CentralControl_9)
        self.frame_CentralBottom_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralBottom_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralBottom_9.setObjectName("frame_CentralBottom_9")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_CentralBottom_9)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_37.addWidget(self.frame_CentralBottom_9)
        self.verticalLayout_36.addWidget(self.frame_CentralControl_9)
        self.stackedWidget_Control_2.addWidget(self.page_Assets_2)
        self.page_Report_2 = QtWidgets.QWidget()
        self.page_Report_2.setStyleSheet("QWidget{\n"
"    background-color:#fafbfd;\n"
"    border:0px;\n"
"}")
        self.page_Report_2.setObjectName("page_Report_2")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.page_Report_2)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.frame_CentralControl_10 = QtWidgets.QFrame(self.page_Report_2)
        self.frame_CentralControl_10.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#fafbfd;\n"
"   border:0px;\n"
"}")
        self.frame_CentralControl_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralControl_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralControl_10.setObjectName("frame_CentralControl_10")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_CentralControl_10)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.frame_18 = QtWidgets.QFrame(self.frame_CentralControl_10)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_10 = QtWidgets.QLabel(self.frame_18)
        self.label_10.setStyleSheet("QLabel{\n"
"\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"\n"
"\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_32.addWidget(self.label_10)
        self.verticalLayout_39.addWidget(self.frame_18)
        self.frame_CentralBottom_10 = QtWidgets.QFrame(self.frame_CentralControl_10)
        self.frame_CentralBottom_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralBottom_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralBottom_10.setObjectName("frame_CentralBottom_10")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_CentralBottom_10)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout_39.addWidget(self.frame_CentralBottom_10)
        self.verticalLayout_38.addWidget(self.frame_CentralControl_10)
        self.stackedWidget_Control_2.addWidget(self.page_Report_2)
        self.page_Config_2 = QtWidgets.QWidget()
        self.page_Config_2.setStyleSheet("QWidget{\n"
"    background-color:#fafbfd;\n"
"    border:0px;\n"
"}")
        self.page_Config_2.setObjectName("page_Config_2")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.page_Config_2)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setSpacing(0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.frame_CentralControl_11 = QtWidgets.QFrame(self.page_Config_2)
        self.frame_CentralControl_11.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#fafbfd;\n"
"   border:0px;\n"
"}")
        self.frame_CentralControl_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralControl_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralControl_11.setObjectName("frame_CentralControl_11")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_CentralControl_11)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.frame_19 = QtWidgets.QFrame(self.frame_CentralControl_11)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_11 = QtWidgets.QLabel(self.frame_19)
        self.label_11.setStyleSheet("QLabel{\n"
"\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_34.addWidget(self.label_11)
        self.verticalLayout_41.addWidget(self.frame_19)
        self.frame_CentralBottom_11 = QtWidgets.QFrame(self.frame_CentralControl_11)
        self.frame_CentralBottom_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralBottom_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralBottom_11.setObjectName("frame_CentralBottom_11")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_CentralBottom_11)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.verticalLayout_41.addWidget(self.frame_CentralBottom_11)
        self.verticalLayout_40.addWidget(self.frame_CentralControl_11)
        self.stackedWidget_Control_2.addWidget(self.page_Config_2)
        self.page_About_2 = QtWidgets.QWidget()
        self.page_About_2.setStyleSheet("QWidget{\n"
"    background-color:#fafbfd;\n"
"    border:0px;\n"
"}")
        self.page_About_2.setObjectName("page_About_2")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.page_About_2)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setSpacing(0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.frame_CentralControl_12 = QtWidgets.QFrame(self.page_About_2)
        self.frame_CentralControl_12.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#fafbfd;\n"
"   border:0px;\n"
"}")
        self.frame_CentralControl_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralControl_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralControl_12.setObjectName("frame_CentralControl_12")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_CentralControl_12)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_20 = QtWidgets.QFrame(self.frame_CentralControl_12)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_12 = QtWidgets.QLabel(self.frame_20)
        self.label_12.setStyleSheet("QLabel{\n"
"\n"
"        font-size:30px;\n"
"        border:0px;\n"
"    font-weight: bold;\n"
"\n"
"\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_36.addWidget(self.label_12)
        self.verticalLayout_43.addWidget(self.frame_20)
        self.frame_CentralBottom_12 = QtWidgets.QFrame(self.frame_CentralControl_12)
        self.frame_CentralBottom_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralBottom_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralBottom_12.setObjectName("frame_CentralBottom_12")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_CentralBottom_12)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.verticalLayout_43.addWidget(self.frame_CentralBottom_12)
        self.verticalLayout_42.addWidget(self.frame_CentralControl_12)
        self.stackedWidget_Control_2.addWidget(self.page_About_2)
        self.verticalLayout_23.addWidget(self.stackedWidget_Control_2)

        self.retranslateUi(Form)
        self.stackedWidget_Control_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_PerfilName_2.setText(_translate("Form", "admin"))
        self.pushButton_Notifications_2.setText(_translate("Form", "25"))
        self.label_LastAccess_2.setText(_translate("Form", "Last access: 30-09-2020 05:01"))
        self.label_LogoNameDesc.setText(_translate("Form", "Tramontinas tool"))
        self.label_LogoName.setText(_translate("Form", "DashPriv8"))
        self.pushButton_DashBoard.setText(_translate("Form", "Dashboard"))
        self.pushButton_QuickStart.setText(_translate("Form", "Quick Start"))
        self.pushButton_Assets.setText(_translate("Form", "Assets"))
        self.pushButton_Report.setText(_translate("Form", "Report"))
        self.pushButton_Config.setText(_translate("Form", "Config"))
        self.pushButton_About.setText(_translate("Form", "About"))
        self.label_IpInfo_2.setText(_translate("Form", "192.168.100.16  | Amsterdam | NL"))
        self.label_Hello_2.setText(_translate("Form", "> Hello Mr. admin"))
        self.label_DashHostDiscovered_2.setText(_translate("Form", "文件"))
        self.label_CountDashHostDiscovered_2.setText(_translate("Form", "0"))
        self.label_DashScanExecuted_2.setText(_translate("Form", "函数"))
        self.label_CountDashScanExecuted_2.setText(_translate("Form", "0"))
        self.label_DashDomains_2.setText(_translate("Form", "变量"))
        self.label_CountDashDomains_2.setText(_translate("Form", "0"))
        self.label_DashHostDiscovered_9.setText(_translate("Form", "风险函数"))
        self.label_CountDashTotalVuln_2.setText(_translate("Form", "0"))
        self.lbl_Vulnerabilities_2.setText(_translate("Form", "风险函数一览"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(11)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(12)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(13)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(14)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(15)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(16)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(17)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(18)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(19)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(20)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(21)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.verticalHeaderItem(22)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "函数名"))
        item = self.tableWidget_Vulnerabilities_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "危险等级"))
        item = self.tableWidget_Vulnerabilities_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "解决方法"))
        __sortingEnabled = self.tableWidget_Vulnerabilities_2.isSortingEnabled()
        self.tableWidget_Vulnerabilities_2.setSortingEnabled(False)
        item = self.tableWidget_Vulnerabilities_2.item(16, 0)
        item.setText(_translate("Form", "216.58.202.101"))
        item = self.tableWidget_Vulnerabilities_2.item(16, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities_2.item(16, 2)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities_2.item(17, 0)
        item.setText(_translate("Form", "216.58.202.128"))
        item = self.tableWidget_Vulnerabilities_2.item(17, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities_2.item(17, 2)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities_2.item(18, 0)
        item.setText(_translate("Form", "216.58.202.129"))
        item = self.tableWidget_Vulnerabilities_2.item(18, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities_2.item(18, 2)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities_2.item(19, 0)
        item.setText(_translate("Form", "216.58.202.135"))
        item = self.tableWidget_Vulnerabilities_2.item(19, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities_2.item(19, 2)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities_2.item(20, 0)
        item.setText(_translate("Form", "216.58.202.137"))
        item = self.tableWidget_Vulnerabilities_2.item(20, 1)
        item.setText(_translate("Form", "139"))
        item = self.tableWidget_Vulnerabilities_2.item(20, 2)
        item.setText(_translate("Form", "Checks for Remote Management Ports"))
        item = self.tableWidget_Vulnerabilities_2.item(21, 0)
        item.setText(_translate("Form", "216.58.202.138"))
        item = self.tableWidget_Vulnerabilities_2.item(21, 1)
        item.setText(_translate("Form", "8080"))
        item = self.tableWidget_Vulnerabilities_2.item(21, 2)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities_2.item(22, 0)
        item.setText(_translate("Form", "216.58.202.139"))
        item = self.tableWidget_Vulnerabilities_2.item(22, 1)
        item.setText(_translate("Form", "445"))
        item = self.tableWidget_Vulnerabilities_2.item(22, 2)
        item.setText(_translate("Form", "Checks for SBM Ports"))
        self.tableWidget_Vulnerabilities_2.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("Form", "QUICK START"))
        self.label_9.setText(_translate("Form", "ASSETS"))
        self.label_10.setText(_translate("Form", "REPORT"))
        self.label_11.setText(_translate("Form", "CONFIG"))
        self.label_12.setText(_translate("Form", "ABOUT"))


    def auto_shape(self):
        mysql = SQL()
        result = mysql.find_all_risk_function(mysql.cursor)
        lines = 0
        self.tableWidget_Vulnerabilities_2.setRowCount(1)
        self.label_CountDashTotalVuln_2.setText(str(33))
        self.label_CountDashDomains_2.setText(str(6))
        self.label_CountDashScanExecuted_2.setText(str(7))
        self.label_CountDashHostDiscovered_2.setText(str(3))
        for re in result:
                re = list(re)
                self.tableWidget_Vulnerabilities_2.setItem(lines, 0, QTableWidgetItem(re[1]))
                self.tableWidget_Vulnerabilities_2.setItem(lines, 1, QTableWidgetItem(re[2]))
                self.tableWidget_Vulnerabilities_2.setItem(lines, 2, QTableWidgetItem(re[3]))
                lines = lines +1
                self.tableWidget_Vulnerabilities_2.setRowCount(lines)



    def showEvent(self, event):
        self.auto_shape()
        event.accept()
