# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Find.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QTableWidgetItem
from PyQt5 import QtCore, QtWidgets
from threading import Thread
from FunctionManagement.SearchAndReplace import replace, search


class Ui_Dialog(QtWidgets.QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(671, 506)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 400, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(510, 60, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 120, 100, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 100, 400, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 160, 200, 30))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 210, 671, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.find_keyword) # type: ignore
        self.pushButton_3.clicked.connect(self.replace_keyword) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "查找和替换"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "查找语句"))
        self.pushButton.setText(_translate("Dialog", "查找"))
        self.pushButton_3.setText(_translate("Dialog", "替换"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "替换语句"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "位置信息"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "关键字个数"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "查找当前行信息"))


    def find_keyword(self):
        self.keyword = self.lineEdit.text()
        self.thread = Thread(target=self.search)
        self.thread.start()

    def search(self):
        folderPath = "G:\桌面\CodeAudit\File"
        result = search.search_keywords_in_folder(folderPath, self.keyword)
        total_count = sum(len(matches) for matches in result.values())
        lines = 0
        for file_path, matches in result.items():
            self.tableWidget.setRowCount(total_count)
            for match in matches:
                self.tableWidget.setItem(lines, 0, QTableWidgetItem(file_path))
                self.tableWidget.setItem(lines, 1, QTableWidgetItem(f"Line {match['line_num']}"))
                self.tableWidget.setItem(lines, 2, QTableWidgetItem(str(total_count)))
                self.tableWidget.setItem(lines,3,QTableWidgetItem(f"{match['line_content']}"))
                lines = lines + 1
    def replace_keyword(self):
        self.keyword = self.lineEdit.text()
        self.thread3 = Thread(target=self.replace)
        self.thread3.start()

    def replace(self):
        folderPath = "E:\Data\PyCharm\CodeAudit\File"
        self.keyword = self.lineEdit.text()
        self.relace = self.lineEdit_2.text()
        replace.replace_keywords_in_project(folderPath, self.keyword, self.relace)