# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtCore import QModelIndex
import os
import sys
from PyQt5.QtWidgets import QFileSystemModel, QTableWidgetItem, QTreeWidgetItem
from PyQt5.QtCore import QDir
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from threading import Thread
from Tools import RelativePath
from Tools import Tree
from FunctionAndVariableDetection.ExtractFunctions import process_c_files
from FunctionAndVariableDetection.DirectoryTree import directory_tree
from Tools.DatabaseOperation import SQL


def count_lines(file_path):
    line_count = 0
    with open(file_path, 'r') as file:
        for line in file:
            line_count += 1
    return line_count

def calculate_risk_level(line_count):
    # 根据行数确定风险水平
    if line_count <= 100:
        return 'Low'
    elif line_count <= 500:
        return 'Medium'
    else:
        return 'High'

class Ui_Form(QtWidgets.QWidget):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1305, 693)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 1311, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.splitter_3 = QtWidgets.QSplitter(self.tab)
        self.splitter_3.setGeometry(QtCore.QRect(0, 0, 1232, 677))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.treeView_2 = QtWidgets.QTreeView(self.splitter_3)
        self.treeView_2.setObjectName("treeView_2")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.splitter_5)
        self.tabWidget_4.setTabsClosable(True)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.splitter_5)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_8 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.tab_8.setFont(font)
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.tableWidget_2)
        self.tabWidget_5.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.tab_9.setFont(font)
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.tabWidget_5.addTab(self.tab_9, "")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.splitter_3)
        self.treeWidget_3.setStyleSheet("QTreeView::branch:closed:has-children\n"
                                        "{\n"
                                        "    image: url(./resource/icon/expand-positive.png);/*图标*/\n"
                                        "    border-image: none;\n"
                                        "}\n"
                                        "\n"
                                        "QTreeView::branch:open:has-children\n"
                                        "{\n"
                                        "    image: url(./resource/icon/shrink-positive.png);/*图标*/\n"
                                        "    border-image: none;\n"
                                        "}")
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.treeWidget_3.header().setDefaultSectionSize(110)
        self.treeWidget_3.header().setHighlightSections(False)
        self.treeWidget_3.header().setMinimumSectionSize(30)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(1230, -8, 75, 691))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 130, 200, 30))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(470, 10, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 90, 200, 30))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 70, 100, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 50, 400, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 130, 100, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(190, 130, 200, 30))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 10, 400, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.treeView_3 = QtWidgets.QTreeView(self.tab_2)
        self.treeView_3.setGeometry(QtCore.QRect(650, 0, 561, 191))
        self.treeView_3.setObjectName("treeView_3")
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget_4.setGeometry(QtCore.QRect(10, 210, 1201, 441))
        self.treeWidget_4.setStyleSheet("QTreeView::branch:closed:has-children\n"
                                        "{\n"
                                        "    image: url(./resource/icon/expand-positive.png);/*图标*/\n"
                                        "    border-image: none;\n"
                                        "}\n"
                                        "\n"
                                        "QTreeView::branch:open:has-children\n"
                                        "{\n"
                                        "    image: url(./resource/icon/shrink-positive.png);/*图标*/\n"
                                        "    border-image: none;\n"
                                        "}")
        self.treeWidget_4.setObjectName("treeWidget_4")
        self.treeWidget_4.header().setDefaultSectionSize(110)
        self.treeWidget_4.header().setHighlightSections(False)
        self.treeWidget_4.header().setMinimumSectionSize(30)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(400, 30, 150, 30))
        self.label_2.setObjectName("label_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(720, 110, 300, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(400, 110, 150, 32))
        self.comboBox.setStyleSheet("min-height:30px")
        self.comboBox.setIconSize(QtCore.QSize(30, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(1060, 40, 121, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 130, 30))
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(1060, 110, 121, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 110, 130, 30))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(20, 180, 1161, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(740, 40, 150, 30))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.treeView_4 = QtWidgets.QTreeView(self.tab_5)
        self.treeView_4.setGeometry(QtCore.QRect(20, 20, 1181, 411))
        self.treeView_4.setObjectName("treeView_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(520, 460, 121, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_Vulnerabilities = QtWidgets.QFrame(self.tab_4)
        self.frame_Vulnerabilities.setGeometry(QtCore.QRect(0, 270, 1221, 371))
        self.frame_Vulnerabilities.setStyleSheet("QFrame{\n"
                                                 "border:1px solid #edf2fa;\n"
                                                 "background-color:#fff;\n"
                                                 "border-radius:10px;\n"
                                                 "}")
        self.frame_Vulnerabilities.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Vulnerabilities.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Vulnerabilities.setObjectName("frame_Vulnerabilities")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_Vulnerabilities)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_Vulnerabilities = QtWidgets.QLabel(self.frame_Vulnerabilities)
        self.lbl_Vulnerabilities.setStyleSheet("QLabel{\n"
                                               "\n"
                                               "        font-size:25px;\n"
                                               "    border:0px;\n"
                                               "\n"
                                               "}")
        self.lbl_Vulnerabilities.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_Vulnerabilities.setObjectName("lbl_Vulnerabilities")
        self.verticalLayout_4.addWidget(self.lbl_Vulnerabilities)
        self.lbl_VulnerabilitiesDesc = QtWidgets.QLabel(self.frame_Vulnerabilities)
        self.lbl_VulnerabilitiesDesc.setStyleSheet("QLabel{\n"
                                                   "\n"
                                                   "    font-size:16px;\n"
                                                   "    border:0px;\n"
                                                   "color:rgb(204, 207, 211);\n"
                                                   "\n"
                                                   "}")
        self.lbl_VulnerabilitiesDesc.setObjectName("lbl_VulnerabilitiesDesc")
        self.verticalLayout_4.addWidget(self.lbl_VulnerabilitiesDesc)
        self.tableWidget_Vulnerabilities = QtWidgets.QTableWidget(self.frame_Vulnerabilities)
        self.tableWidget_Vulnerabilities.setStyleSheet("QTableWidget {    \n"
                                                       "    background-color: #fff;\n"
                                                       "    padding: 10px;\n"
                                                       "    gridline-color: rgb(44, 49, 60);\n"
                                                       "    border-bottom: 1px solid rgb(204, 207, 211);\n"
                                                       "    color:#000;\n"
                                                       "}\n"
                                                       "QTableWidget::item{\n"
                                                       "    border-color: rgb(44, 49, 60);\n"
                                                       "    padding-left: 5px;\n"
                                                       "    padding-right: 5px;\n"
                                                       "    gridline-color: rgb(44, 49, 60);\n"
                                                       "}\n"
                                                       "QTableWidget::item:selected{\n"
                                                       "    background-color: #e5faf8;\n"
                                                       "    color:#000;\n"
                                                       "}\n"
                                                       "QScrollBar:horizontal {\n"
                                                       "    border: none;\n"
                                                       "    background: rgb(52, 59, 72);\n"
                                                       "    height: 14px;\n"
                                                       "    margin: 0px 21px 0 21px;\n"
                                                       "    border-radius: 0px;\n"
                                                       "}\n"
                                                       " QScrollBar:vertical {\n"
                                                       "    border: none;\n"
                                                       "    background: rgb(52, 59, 72);\n"
                                                       "    width: 14px;\n"
                                                       "    margin: 21px 0 21px 0;\n"
                                                       "    border-radius: 0px;\n"
                                                       " }\n"
                                                       "QHeaderView{\n"
                                                       "   background-color:#04c9b7;\n"
                                                       "    border: 1px solid rgb(204, 207, 211);\n"
                                                       "    border-style: none;\n"
                                                       "    border-bottom: 1px solid rgb(204, 207, 211);\n"
                                                       "    border-right: 1px solid rgb(204, 207, 211);\n"
                                                       "    color:#fff;\n"
                                                       "    font-size:15px;\n"
                                                       "    border-radius: 0px;\n"
                                                       "}\n"
                                                       "")
        self.tableWidget_Vulnerabilities.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Vulnerabilities.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Vulnerabilities.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_Vulnerabilities.setShowGrid(True)
        self.tableWidget_Vulnerabilities.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_Vulnerabilities.setObjectName("tableWidget_Vulnerabilities")
        self.tableWidget_Vulnerabilities.setColumnCount(4)
        self.tableWidget_Vulnerabilities.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(17, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(18, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(19, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(20, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(21, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(150, 24, 55))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_Vulnerabilities.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Vulnerabilities.setItem(22, 3, item)
        self.tableWidget_Vulnerabilities.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Vulnerabilities.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Vulnerabilities.verticalHeader().setVisible(False)
        self.tableWidget_Vulnerabilities.verticalHeader().setHighlightSections(True)
        self.verticalLayout_4.addWidget(self.tableWidget_Vulnerabilities)
        self.frame_TopBar = QtWidgets.QFrame(self.tab_4)
        self.frame_TopBar.setGeometry(QtCore.QRect(0, 0, 1231, 55))
        self.frame_TopBar.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_TopBar.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_TopBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_TopBar.setStyleSheet("QFrame{\n"
                                        "background-color: #ffffff;\n"
                                        "border:1px solid #edf2fa;\n"
                                        "}")
        self.frame_TopBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopBar.setObjectName("frame_TopBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_TopBar)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_PerfilName = QtWidgets.QLabel(self.frame_TopBar)
        self.label_PerfilName.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_PerfilName.setStyleSheet("QLabel{\n"
                                            "color:rgb(204, 207, 211);\n"
                                            "    font-size:15px;\n"
                                            "    border:0px;\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "")
        self.label_PerfilName.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_PerfilName.setObjectName("label_PerfilName")
        self.horizontalLayout_5.addWidget(self.label_PerfilName)
        self.pushButton_Perfil = QtWidgets.QPushButton(self.frame_TopBar)
        self.pushButton_Perfil.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_Perfil.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_Perfil.setStyleSheet("QPushButton{\n"
                                             "background-color:#e5faf8;\n"
                                             "border:0px;\n"
                                             "border-radius:10px;\n"
                                             "}")
        self.pushButton_Perfil.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/user-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Perfil.setIcon(icon)
        self.pushButton_Perfil.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Perfil.setObjectName("pushButton_Perfil")
        self.horizontalLayout_5.addWidget(self.pushButton_Perfil)
        self.pushButton_Notifications = QtWidgets.QPushButton(self.frame_TopBar)
        self.pushButton_Notifications.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_Notifications.setMaximumSize(QtCore.QSize(50, 30))
        self.pushButton_Notifications.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Notifications.setStyleSheet("QPushButton{\n"
                                                    "background-color:#e5faf8;\n"
                                                    "border:0px;\n"
                                                    "border-radius:10px;\n"
                                                    "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Notifications.setIcon(icon1)
        self.pushButton_Notifications.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Notifications.setObjectName("pushButton_Notifications")
        self.horizontalLayout_5.addWidget(self.pushButton_Notifications)
        self.frame_TopBarSpace = QtWidgets.QFrame(self.frame_TopBar)
        self.frame_TopBarSpace.setStyleSheet("QFrame{border:0px;}")
        self.frame_TopBarSpace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopBarSpace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopBarSpace.setObjectName("frame_TopBarSpace")
        self.horizontalLayout_5.addWidget(self.frame_TopBarSpace)
        self.label_LastAccess = QtWidgets.QLabel(self.frame_TopBar)
        self.label_LastAccess.setMinimumSize(QtCore.QSize(160, 0))
        self.label_LastAccess.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_LastAccess.setStyleSheet("QLabel{\n"
                                            "color:rgb(204, 207, 211);\n"
                                            "    font-size:15px;\n"
                                            "    border:0px;\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "")
        self.label_LastAccess.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_LastAccess.setObjectName("label_LastAccess")
        self.horizontalLayout_5.addWidget(self.label_LastAccess)
        self.pushButton_LastAccess = QtWidgets.QPushButton(self.frame_TopBar)
        self.pushButton_LastAccess.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_LastAccess.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_LastAccess.setStyleSheet("QPushButton{\n"
                                                 "background-color:#e5faf8;\n"
                                                 "border:0px;\n"
                                                 "border-radius:10px;\n"
                                                 "}")
        self.pushButton_LastAccess.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/clock-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LastAccess.setIcon(icon2)
        self.pushButton_LastAccess.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_LastAccess.setObjectName("pushButton_LastAccess")
        self.horizontalLayout_5.addWidget(self.pushButton_LastAccess)
        self.label_IpInfo = QtWidgets.QLabel(self.frame_TopBar)
        self.label_IpInfo.setMinimumSize(QtCore.QSize(160, 0))
        self.label_IpInfo.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_IpInfo.setStyleSheet("QLabel{\n"
                                        "color:rgb(204, 207, 211);\n"
                                        "    font-size:15px;\n"
                                        "    border:0px;\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "")
        self.label_IpInfo.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_IpInfo.setObjectName("label_IpInfo")
        self.horizontalLayout_5.addWidget(self.label_IpInfo)
        self.pushButton_InfoIo = QtWidgets.QPushButton(self.frame_TopBar)
        self.pushButton_InfoIo.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_InfoIo.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_InfoIo.setStyleSheet("QPushButton{\n"
                                             "background-color:#e5faf8;\n"
                                             "border:0px;\n"
                                             "border-radius:10px;\n"
                                             "}")
        self.pushButton_InfoIo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/placeholder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_InfoIo.setIcon(icon3)
        self.pushButton_InfoIo.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_InfoIo.setObjectName("pushButton_InfoIo")
        self.horizontalLayout_5.addWidget(self.pushButton_InfoIo)
        self.frame_CentralTop = QtWidgets.QFrame(self.tab_4)
        self.frame_CentralTop.setGeometry(QtCore.QRect(0, 50, 1231, 220))
        self.frame_CentralTop.setMinimumSize(QtCore.QSize(0, 220))
        self.frame_CentralTop.setMaximumSize(QtCore.QSize(16777215, 220))
        self.frame_CentralTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralTop.setObjectName("frame_CentralTop")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_CentralTop)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_DashHostDiscovered_2 = QtWidgets.QFrame(self.frame_CentralTop)
        self.frame_DashHostDiscovered_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_DashHostDiscovered_2.setStyleSheet("QFrame{\n"
                                                      "border:1px solid #edf2fa;\n"
                                                      "background-color:#fff;\n"
                                                      "border-radius:10px;\n"
                                                      "text-align:center;\n"
                                                      "}")
        self.frame_DashHostDiscovered_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashHostDiscovered_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashHostDiscovered_2.setObjectName("frame_DashHostDiscovered_2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_DashHostDiscovered_2)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_DashHostDiscovered_2 = QtWidgets.QLabel(self.frame_DashHostDiscovered_2)
        self.label_DashHostDiscovered_2.setStyleSheet("QLabel{\n"
                                                      "\n"
                                                      "    font-size:20px;\n"
                                                      "    border:0px;\n"
                                                      "\n"
                                                      "}")
        self.label_DashHostDiscovered_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DashHostDiscovered_2.setObjectName("label_DashHostDiscovered_2")
        self.verticalLayout_23.addWidget(self.label_DashHostDiscovered_2)
        self.frame_12 = QtWidgets.QFrame(self.frame_DashHostDiscovered_2)
        self.frame_12.setStyleSheet("QFrame{border:0px;}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_DashHostDiscovered_2 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_DashHostDiscovered_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_DashHostDiscovered_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_DashHostDiscovered_2.setStyleSheet("QPushButton{\n"
                                                           "background-color:#04c9b7;\n"
                                                           "border:0px;\n"
                                                           "border-radius:10px;\n"
                                                           "}")
        self.pushButton_DashHostDiscovered_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/star-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashHostDiscovered_2.setIcon(icon4)
        self.pushButton_DashHostDiscovered_2.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_DashHostDiscovered_2.setObjectName("pushButton_DashHostDiscovered_2")
        self.horizontalLayout_20.addWidget(self.pushButton_DashHostDiscovered_2)
        self.label_CountDashHostDiscovered_2 = QtWidgets.QLabel(self.frame_12)
        self.label_CountDashHostDiscovered_2.setStyleSheet("QLabel{\n"
                                                           "\n"
                                                           "    font-size:30px;\n"
                                                           "    border:0px;\n"
                                                           "    font-weight: bold;\n"
                                                           "\n"
                                                           "}")
        self.label_CountDashHostDiscovered_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CountDashHostDiscovered_2.setObjectName("label_CountDashHostDiscovered_2")
        self.horizontalLayout_20.addWidget(self.label_CountDashHostDiscovered_2)
        self.verticalLayout_23.addWidget(self.frame_12)
        self.frame_Line_2 = QtWidgets.QFrame(self.frame_DashHostDiscovered_2)
        self.frame_Line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Line_2.setStyleSheet("QFrame{\n"
                                        "border:0px;\n"
                                        "background-color:#edf2fa;\n"
                                        "border-radius:0px;\n"
                                        "}")
        self.frame_Line_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Line_2.setObjectName("frame_Line_2")
        self.verticalLayout_23.addWidget(self.frame_Line_2)
        self.label_DescDashHostDiscovered_2 = QtWidgets.QLabel(self.frame_DashHostDiscovered_2)
        self.label_DescDashHostDiscovered_2.setStyleSheet("QLabel{\n"
                                                          "\n"
                                                          "    font-size:16px;\n"
                                                          "    border:0px;\n"
                                                          "color:rgb(204, 207, 211);\n"
                                                          "\n"
                                                          "}")
        self.label_DescDashHostDiscovered_2.setObjectName("label_DescDashHostDiscovered_2")
        self.verticalLayout_23.addWidget(self.label_DescDashHostDiscovered_2)
        self.horizontalLayout_4.addWidget(self.frame_DashHostDiscovered_2)
        self.frame_CentralSpace1_2 = QtWidgets.QFrame(self.frame_CentralTop)
        self.frame_CentralSpace1_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_CentralSpace1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralSpace1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralSpace1_2.setObjectName("frame_CentralSpace1_2")
        self.horizontalLayout_4.addWidget(self.frame_CentralSpace1_2)
        self.frame_DashScanExecuted_2 = QtWidgets.QFrame(self.frame_CentralTop)
        self.frame_DashScanExecuted_2.setStyleSheet("QFrame{\n"
                                                    "border:1px solid #edf2fa;\n"
                                                    "background-color:#fff;\n"
                                                    "border-radius:10px;\n"
                                                    "}")
        self.frame_DashScanExecuted_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashScanExecuted_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashScanExecuted_2.setObjectName("frame_DashScanExecuted_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_DashScanExecuted_2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_DashScanExecuted_2 = QtWidgets.QLabel(self.frame_DashScanExecuted_2)
        self.label_DashScanExecuted_2.setStyleSheet("QLabel{\n"
                                                    "\n"
                                                    "    font-size:20px;\n"
                                                    "    border:0px;\n"
                                                    "\n"
                                                    "}")
        self.label_DashScanExecuted_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DashScanExecuted_2.setObjectName("label_DashScanExecuted_2")
        self.verticalLayout_24.addWidget(self.label_DashScanExecuted_2)
        self.frame_13 = QtWidgets.QFrame(self.frame_DashScanExecuted_2)
        self.frame_13.setStyleSheet("QFrame{border:0px;}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_DashScanExecuted_2 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_DashScanExecuted_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_DashScanExecuted_2.setStyleSheet("QPushButton{\n"
                                                         "background-color:#04c9b7;\n"
                                                         "border:0px;\n"
                                                         "border-radius:10px;\n"
                                                         "}")
        self.pushButton_DashScanExecuted_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/search-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashScanExecuted_2.setIcon(icon5)
        self.pushButton_DashScanExecuted_2.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_DashScanExecuted_2.setObjectName("pushButton_DashScanExecuted_2")
        self.horizontalLayout_21.addWidget(self.pushButton_DashScanExecuted_2)
        self.label_CountDashScanExecuted_2 = QtWidgets.QLabel(self.frame_13)
        self.label_CountDashScanExecuted_2.setStyleSheet("QLabel{\n"
                                                         "\n"
                                                         "    font-size:30px;\n"
                                                         "    border:0px;\n"
                                                         "    font-weight: bold;\n"
                                                         "\n"
                                                         "}")
        self.label_CountDashScanExecuted_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CountDashScanExecuted_2.setObjectName("label_CountDashScanExecuted_2")
        self.horizontalLayout_21.addWidget(self.label_CountDashScanExecuted_2)
        self.verticalLayout_24.addWidget(self.frame_13)
        self.frame_Line_4 = QtWidgets.QFrame(self.frame_DashScanExecuted_2)
        self.frame_Line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Line_4.setStyleSheet("QFrame{\n"
                                        "border:0px;\n"
                                        "background-color:#edf2fa;\n"
                                        "border-radius:0px;\n"
                                        "}")
        self.frame_Line_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Line_4.setObjectName("frame_Line_4")
        self.verticalLayout_24.addWidget(self.frame_Line_4)
        self.label_DescDashScanExecuted_2 = QtWidgets.QLabel(self.frame_DashScanExecuted_2)
        self.label_DescDashScanExecuted_2.setStyleSheet("QLabel{\n"
                                                        "\n"
                                                        "    font-size:16px;\n"
                                                        "    border:0px;\n"
                                                        "color:rgb(204, 207, 211);\n"
                                                        "\n"
                                                        "}")
        self.label_DescDashScanExecuted_2.setObjectName("label_DescDashScanExecuted_2")
        self.verticalLayout_24.addWidget(self.label_DescDashScanExecuted_2)
        self.horizontalLayout_4.addWidget(self.frame_DashScanExecuted_2)
        self.frame_CentralSpace2_2 = QtWidgets.QFrame(self.frame_CentralTop)
        self.frame_CentralSpace2_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_CentralSpace2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralSpace2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralSpace2_2.setObjectName("frame_CentralSpace2_2")
        self.horizontalLayout_4.addWidget(self.frame_CentralSpace2_2)
        self.frame_CentralSpace3_2 = QtWidgets.QFrame(self.frame_CentralTop)
        self.frame_CentralSpace3_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_CentralSpace3_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CentralSpace3_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CentralSpace3_2.setObjectName("frame_CentralSpace3_2")
        self.horizontalLayout_4.addWidget(self.frame_CentralSpace3_2)
        self.frame_DashTotalVuln_2 = QtWidgets.QFrame(self.frame_CentralTop)
        self.frame_DashTotalVuln_2.setStyleSheet("QFrame{\n"
                                                 "border:1px solid #edf2fa;\n"
                                                 "background-color:#fff;\n"
                                                 "border-radius:10px;\n"
                                                 "}")
        self.frame_DashTotalVuln_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DashTotalVuln_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DashTotalVuln_2.setObjectName("frame_DashTotalVuln_2")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_DashTotalVuln_2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_DashHostDiscovered_9 = QtWidgets.QLabel(self.frame_DashTotalVuln_2)
        self.label_DashHostDiscovered_9.setStyleSheet("QLabel{\n"
                                                      "\n"
                                                      "    font-size:20px;\n"
                                                      "    border:0px;\n"
                                                      "\n"
                                                      "}")
        self.label_DashHostDiscovered_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DashHostDiscovered_9.setObjectName("label_DashHostDiscovered_9")
        self.verticalLayout_26.addWidget(self.label_DashHostDiscovered_9)
        self.frame_15 = QtWidgets.QFrame(self.frame_DashTotalVuln_2)
        self.frame_15.setStyleSheet("QFrame{border:0px;}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_DashTotalVuln_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_DashTotalVuln_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_DashTotalVuln_2.setStyleSheet("QPushButton{\n"
                                                      "background-color:#04c9b7;\n"
                                                      "border:0px;\n"
                                                      "border-radius:10px;\n"
                                                      "}")
        self.pushButton_DashTotalVuln_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DashTotalVuln_2.setIcon(icon6)
        self.pushButton_DashTotalVuln_2.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_DashTotalVuln_2.setObjectName("pushButton_DashTotalVuln_2")
        self.horizontalLayout_23.addWidget(self.pushButton_DashTotalVuln_2)
        self.label_CountDashTotalVuln_2 = QtWidgets.QLabel(self.frame_15)
        self.label_CountDashTotalVuln_2.setStyleSheet("QLabel{\n"
                                                      "\n"
                                                      "    font-size:30px;\n"
                                                      "    border:0px;\n"
                                                      "    font-weight: bold;\n"
                                                      "\n"
                                                      "}")
        self.label_CountDashTotalVuln_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CountDashTotalVuln_2.setObjectName("label_CountDashTotalVuln_2")
        self.horizontalLayout_23.addWidget(self.label_CountDashTotalVuln_2)
        self.verticalLayout_26.addWidget(self.frame_15)
        self.frame_Line_9 = QtWidgets.QFrame(self.frame_DashTotalVuln_2)
        self.frame_Line_9.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Line_9.setStyleSheet("QFrame{\n"
                                        "border:0px;\n"
                                        "background-color:#edf2fa;\n"
                                        "border-radius:0px;\n"
                                        "}")
        self.frame_Line_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Line_9.setObjectName("frame_Line_9")
        self.verticalLayout_26.addWidget(self.frame_Line_9)
        self.label_DescDashTotalVuln_2 = QtWidgets.QLabel(self.frame_DashTotalVuln_2)
        self.label_DescDashTotalVuln_2.setStyleSheet("QLabel{\n"
                                                     "\n"
                                                     "    font-size:16px;\n"
                                                     "    border:0px;\n"
                                                     "color:rgb(204, 207, 211);\n"
                                                     "\n"
                                                     "}")
        self.label_DescDashTotalVuln_2.setObjectName("label_DescDashTotalVuln_2")
        self.verticalLayout_26.addWidget(self.label_DescDashTotalVuln_2)
        self.horizontalLayout_4.addWidget(self.frame_DashTotalVuln_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(0, 60, 0, 677))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.pushButton_7.clicked.connect(Form.opendirectory)  # type: ignore
        self.pushButton.clicked.connect(Form.find_content)  # type: ignore
        self.pushButton_3.clicked.connect(Form.replace)  # type: ignore
        self.pushButton_4.clicked.connect(Form.replace_all)  # type: ignore
        self.pushButton_2.clicked.connect(Form.add)  # type: ignore
        self.pushButton_5.clicked.connect(Form.delete)  # type: ignore
        self.pushButton_6.clicked.connect(Form.generate_report)  # type: ignore
        self.treeView_2.clicked['QModelIndex'].connect(Form.on_tree_item_clicked)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "文件名"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "行数"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "风险"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_8), _translate("Form", "输出"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_9), _translate("Form", "终端"))
        self.treeWidget_3.headerItem().setText(0, _translate("Form", "函数和变量"))
        self.treeWidget_3.headerItem().setText(1, _translate("Form", "类型"))
        self.pushButton_7.setText(_translate("Form", "打开项目"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "主界面"))
        self.checkBox_2.setText(_translate("Form", "使用循环查找"))
        self.pushButton.setText(_translate("Form", "查找"))
        self.checkBox.setText(_translate("Form", "使用正则表达式"))
        self.pushButton_3.setText(_translate("Form", "替换"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "替换语句"))
        self.pushButton_4.setText(_translate("Form", "替换所有"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "查找语句"))
        self.treeWidget_4.headerItem().setText(0, _translate("Form", "函数和变量"))
        self.treeWidget_4.headerItem().setText(1, _translate("Form", "类型"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "搜索"))
        self.label_2.setText(_translate("Form", "函数危险等级"))
        self.comboBox.setItemText(0, _translate("Form", "低危险"))
        self.comboBox.setItemText(1, _translate("Form", "中等危险"))
        self.comboBox.setItemText(2, _translate("Form", "危险"))
        self.comboBox.setItemText(3, _translate("Form", "很危险（或稍小，取决于实现）"))
        self.comboBox.setItemText(4, _translate("Form", "很危险"))
        self.comboBox.setItemText(5, _translate("Form", "最危险"))
        self.pushButton_2.setText(_translate("Form", "添加"))
        self.label_3.setText(_translate("Form", "函数名"))
        self.pushButton_5.setText(_translate("Form", "删除"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "函数名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "函数危险等级"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "建议解决方法"))
        self.label_4.setText(_translate("Form", "建议解决方法"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "风险函数管理"))
        self.pushButton_6.setText(_translate("Form", "生成报告"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "风险函数报告"))
        self.lbl_Vulnerabilities.setText(_translate("Form", "Vulnerabilities"))
        self.lbl_VulnerabilitiesDesc.setText(_translate("Form", "Last Scanned"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(11)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(12)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(13)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(14)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(15)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(16)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(17)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(18)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(19)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(20)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(21)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.verticalHeaderItem(22)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget_Vulnerabilities.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Target"))
        item = self.tableWidget_Vulnerabilities.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Port"))
        item = self.tableWidget_Vulnerabilities.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Severity"))
        item = self.tableWidget_Vulnerabilities.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Description"))
        __sortingEnabled = self.tableWidget_Vulnerabilities.isSortingEnabled()
        self.tableWidget_Vulnerabilities.setSortingEnabled(False)
        item = self.tableWidget_Vulnerabilities.item(0, 0)
        item.setText(_translate("Form", "192.168.0.1"))
        item = self.tableWidget_Vulnerabilities.item(0, 1)
        item.setText(_translate("Form", "445"))
        item = self.tableWidget_Vulnerabilities.item(0, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(0, 3)
        item.setText(_translate("Form", "Checks for SBM Ports"))
        item = self.tableWidget_Vulnerabilities.item(1, 0)
        item.setText(_translate("Form", "192.168.0.55"))
        item = self.tableWidget_Vulnerabilities.item(1, 1)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_Vulnerabilities.item(1, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(1, 3)
        item.setText(_translate("Form", "Checks if SSH password authentication is supported"))
        item = self.tableWidget_Vulnerabilities.item(2, 0)
        item.setText(_translate("Form", "192.168.0.1"))
        item = self.tableWidget_Vulnerabilities.item(2, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(2, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(2, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(3, 0)
        item.setText(_translate("Form", "192.168.0.140"))
        item = self.tableWidget_Vulnerabilities.item(3, 1)
        item.setText(_translate("Form", "139"))
        item = self.tableWidget_Vulnerabilities.item(3, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(3, 3)
        item.setText(_translate("Form", "Checks for Remote Management Ports"))
        item = self.tableWidget_Vulnerabilities.item(4, 0)
        item.setText(_translate("Form", "192.168.0.11"))
        item = self.tableWidget_Vulnerabilities.item(4, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(4, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(4, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(5, 0)
        item.setText(_translate("Form", "192.168.0.54"))
        item = self.tableWidget_Vulnerabilities.item(5, 1)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_Vulnerabilities.item(5, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(5, 3)
        item.setText(_translate("Form", "Checks if SSH password authentication is supported"))
        item = self.tableWidget_Vulnerabilities.item(6, 0)
        item.setText(_translate("Form", "200.10.0.10"))
        item = self.tableWidget_Vulnerabilities.item(6, 1)
        item.setText(_translate("Form", "445"))
        item = self.tableWidget_Vulnerabilities.item(6, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(6, 3)
        item.setText(_translate("Form", "Checks for SBM Ports"))
        item = self.tableWidget_Vulnerabilities.item(7, 0)
        item.setText(_translate("Form", "200.10.0.15"))
        item = self.tableWidget_Vulnerabilities.item(7, 1)
        item.setText(_translate("Form", "8080"))
        item = self.tableWidget_Vulnerabilities.item(7, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(7, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(8, 0)
        item.setText(_translate("Form", "200.10.0.5"))
        item = self.tableWidget_Vulnerabilities.item(8, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(8, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(8, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(9, 0)
        item.setText(_translate("Form", "200.10.0.113"))
        item = self.tableWidget_Vulnerabilities.item(9, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(9, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(9, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(10, 0)
        item.setText(_translate("Form", "200.10.0.29"))
        item = self.tableWidget_Vulnerabilities.item(10, 1)
        item.setText(_translate("Form", "139"))
        item = self.tableWidget_Vulnerabilities.item(10, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(10, 3)
        item.setText(_translate("Form", "Checks for Remote Management Ports"))
        item = self.tableWidget_Vulnerabilities.item(11, 0)
        item.setText(_translate("Form", "200.10.0.201"))
        item = self.tableWidget_Vulnerabilities.item(11, 1)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_Vulnerabilities.item(11, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(11, 3)
        item.setText(_translate("Form", "Checks if SSH password authentication is supported"))
        item = self.tableWidget_Vulnerabilities.item(12, 0)
        item.setText(_translate("Form", "200.10.0.92"))
        item = self.tableWidget_Vulnerabilities.item(12, 1)
        item.setText(_translate("Form", "445"))
        item = self.tableWidget_Vulnerabilities.item(12, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(12, 3)
        item.setText(_translate("Form", "Checks for SBM Ports"))
        item = self.tableWidget_Vulnerabilities.item(13, 0)
        item.setText(_translate("Form", "216.58.202.14"))
        item = self.tableWidget_Vulnerabilities.item(13, 1)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_Vulnerabilities.item(13, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(13, 3)
        item.setText(_translate("Form", "Checks if SSH password authentication is supported"))
        item = self.tableWidget_Vulnerabilities.item(14, 0)
        item.setText(_translate("Form", "216.58.202.14"))
        item = self.tableWidget_Vulnerabilities.item(14, 1)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_Vulnerabilities.item(14, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(14, 3)
        item.setText(_translate("Form", "Checks if SSH password authentication is supported"))
        item = self.tableWidget_Vulnerabilities.item(15, 0)
        item.setText(_translate("Form", "216.58.202.200"))
        item = self.tableWidget_Vulnerabilities.item(15, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(15, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(15, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(16, 0)
        item.setText(_translate("Form", "216.58.202.101"))
        item = self.tableWidget_Vulnerabilities.item(16, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(16, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(16, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(17, 0)
        item.setText(_translate("Form", "216.58.202.128"))
        item = self.tableWidget_Vulnerabilities.item(17, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(17, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(17, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(18, 0)
        item.setText(_translate("Form", "216.58.202.129"))
        item = self.tableWidget_Vulnerabilities.item(18, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(18, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(18, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(19, 0)
        item.setText(_translate("Form", "216.58.202.135"))
        item = self.tableWidget_Vulnerabilities.item(19, 1)
        item.setText(_translate("Form", "80"))
        item = self.tableWidget_Vulnerabilities.item(19, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(19, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(20, 0)
        item.setText(_translate("Form", "216.58.202.137"))
        item = self.tableWidget_Vulnerabilities.item(20, 1)
        item.setText(_translate("Form", "139"))
        item = self.tableWidget_Vulnerabilities.item(20, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(20, 3)
        item.setText(_translate("Form", "Checks for Remote Management Ports"))
        item = self.tableWidget_Vulnerabilities.item(21, 0)
        item.setText(_translate("Form", "216.58.202.138"))
        item = self.tableWidget_Vulnerabilities.item(21, 1)
        item.setText(_translate("Form", "8080"))
        item = self.tableWidget_Vulnerabilities.item(21, 2)
        item.setText(_translate("Form", "Informational"))
        item = self.tableWidget_Vulnerabilities.item(21, 3)
        item.setText(_translate("Form", "Checks if Security Headers exist"))
        item = self.tableWidget_Vulnerabilities.item(22, 0)
        item.setText(_translate("Form", "216.58.202.139"))
        item = self.tableWidget_Vulnerabilities.item(22, 1)
        item.setText(_translate("Form", "445"))
        item = self.tableWidget_Vulnerabilities.item(22, 2)
        item.setText(_translate("Form", "High"))
        item = self.tableWidget_Vulnerabilities.item(22, 3)
        item.setText(_translate("Form", "Checks for SBM Ports"))
        self.tableWidget_Vulnerabilities.setSortingEnabled(__sortingEnabled)
        self.label_PerfilName.setText(_translate("Form", "MrCl0wnLab"))
        self.pushButton_Notifications.setText(_translate("Form", "25"))
        self.label_LastAccess.setText(_translate("Form", "Last access: 30-09-2020 05:01"))
        self.label_IpInfo.setText(_translate("Form", "185.88.181.4  | Amsterdam | NL"))
        self.label_DashHostDiscovered_2.setText(_translate("Form", "风险函数"))
        self.label_CountDashHostDiscovered_2.setText(_translate("Form", "1506"))
        self.label_DescDashHostDiscovered_2.setText(_translate("Form", "Since Last Assessment"))
        self.label_DashScanExecuted_2.setText(_translate("Form", "风险变量"))
        self.label_CountDashScanExecuted_2.setText(_translate("Form", "3"))
        self.label_DescDashScanExecuted_2.setText(_translate("Form", "Since Last System Reset"))
        self.label_DashHostDiscovered_9.setText(_translate("Form", "Total Vulnerabilities"))
        self.label_CountDashTotalVuln_2.setText(_translate("Form", "658"))
        self.label_DescDashTotalVuln_2.setText(_translate("Form", "Since Last Assessment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Dashboard"))


    def opendirectory(self):
        folderDialog = QFileDialog.getExistingDirectory(self, '打开文件夹')
        self.lines = 0
        if folderDialog:
            # 获取选中的文件夹路径
            self.folderPath = folderDialog
            print(self.folderPath)
            # 进行函数检测
            directory_tree1 = directory_tree(folderDialog)
            # 提取自定义函数和库函数
            functions = process_c_files(directory_tree1, folderDialog)
            # print("函数信息:")
            for function in functions:
                # print(function)
                try:
                    item = QTreeWidgetItem()
                    item.setText(0, function['function_name'] + ';' + function['parameter'])
                    item.setText(1, function['return_type'])
                    #item.setText(1, function['path'])
                    self.treeWidget_3.addTopLevelItem(item)
                except Exception as e:
                    print("发生异常:", str(e))

            self.thread1 = Thread(target=self.generate_tree)
            self.thread1.start()

    def generate_tree(self):
        model = QFileSystemModel()
        model.setRootPath(self.folderPath)
        model.setNameFilters(['*.c'])
        self.treeView_2.setModel(model)

        # 设置 QTreeView 的根索引为项目根目录
        root_index = model.setRootPath(self.folderPath)
        self.treeView_2.setRootIndex(root_index)
        parent_path = model.filePath(root_index)
        for name in os.listdir(parent_path):
            path = os.path.join(parent_path, name)
            index = model.index(path)
            if os.path.isdir(path):
                self.file_system_model = model
                self.populate_directory_tree(index)
            else:
                self.tableWidget_2.setRowCount(self.lines+1)
                self.tableWidget_2.setItem(self.lines,0,QTableWidgetItem(name))
                self.tableWidget_2.setItem(self.lines,1,QTableWidgetItem(str(count_lines(path))))
                self.tableWidget_2.setItem(self.lines,2,QTableWidgetItem(calculate_risk_level(count_lines(path))))
                self.lines = self.lines + 1

    def populate_directory_tree(self, parent_index):
            parent_path = self.file_system_model.filePath(parent_index)
            for name in os.listdir(parent_path):
                    path = os.path.join(parent_path, name)
                    index = self.file_system_model.index(path)
                    if os.path.isdir(path):
                            self.populate_directory_tree(index)
                    else:
                        self.tableWidget_2.setRowCount(self.lines + 1)
                        self.tableWidget_2.setItem(self.lines, 0, QTableWidgetItem(name))
                        self.tableWidget_2.setItem(self.lines, 1, QTableWidgetItem(str(count_lines(path))))
                        self.tableWidget_2.setItem(self.lines, 2,   QTableWidgetItem(calculate_risk_level(count_lines(path))))
                        self.lines = self.lines+1

    def on_tree_item_clicked(self, index: QModelIndex):
        if not index.isValid():
                return

        if index.column() != 0:
                return

        file_path = self.treeView_2.model().filePath(index)
        print(file_path)
        if not file_path:
                return

        try:
                with open(file_path, 'r') as file:
                        file_content = file.read()
                        self.textEdit_3.setPlainText(file_content)
                mysql = SQL()
                ss = mysql.select_scan_function(mysql.cursor)
                for function in ss:
                    # print(function)
                    if(function['path']==file_path):
                        try:
                            item = QTreeWidgetItem()
                            item.setText(0, function['function_name'] + ';' + function['parameter'])
                            item.setText(1, function['return_type'])
                            # item.setText(1, function['path'])
                            self.treeWidget_3.addTopLevelItem(item)
                        except Exception as e:
                            print("发生异常:", str(e))
                mysql.close_SQL(mysql.cursor, mysql.cnx)
        except IOError as e:
                print('无法打开文件:', e)

    def generate_report(self):
        pass

    def delete(self):
        pass

    def replace_all(self):
        pass

    def replace(self):
        pass

    def add(self):
        pass

    def find_content(self):
        pass